# =============================================================================
# Laravel Octane + FrankenPHP - Google Cloud Run
# PHP 8.5 | Multi-stage build (front-end assets was locally compiled)
# =============================================================================

# -----------------------------------------------------------------------------
# Stage 1: Composer dependencies
# -----------------------------------------------------------------------------
FROM composer:2 AS composer

WORKDIR /app

# Copy only dependency files first for better cache
COPY composer.json composer.lock ./

# Install dependencies without dev packages
RUN composer install \
    --no-dev \
    --no-scripts \
    --no-autoloader \
    --ignore-platform-reqs \
    --prefer-dist

# Copy application code
COPY . .

# Generate optimized autoloader
RUN composer dump-autoload --optimize --no-dev --no-scripts

# -----------------------------------------------------------------------------
# Stage 2: Production image with FrankenPHP
# -----------------------------------------------------------------------------
FROM dunglas/frankenphp:php8.5-alpine AS production

ARG APP_KEY

ENV SERVER_NAME=:8080
ENV APP_ENV=production
ENV APP_DEBUG=false
ENV LOG_CHANNEL=stderr
ENV LOG_LEVEL=info
ENV APP_KEY=${APP_KEY}
ENV PORT=8080

WORKDIR /app

# System dependencies
RUN apk add --no-cache \
    curl \
    libpng \
    libjpeg-turbo \
    libwebp \
    freetype \
    icu-libs \
    libzip \
    oniguruma \
    libpq \
    busybox-extras

# PHP extensions
RUN install-php-extensions \
    pcntl \
    pdo_mysql \
    pdo_pgsql \
    pgsql \
    redis \
    gd \
    intl \
    zip \
    bcmath \
    opcache \
    sockets \
    exif

# Create required directories (add /tmp/opcache for PHP 8.5)
RUN mkdir -p \
    storage/logs \
    storage/framework/cache \
    storage/framework/sessions \
    storage/framework/views \
    bootstrap/cache \
    /tmp/opcache

# Copy PHP configuration
COPY docker/php/php.ini $PHP_INI_DIR/conf.d/99-app.ini
COPY docker/php/opcache.ini $PHP_INI_DIR/conf.d/opcache.ini

# Copy dependencies from composer stage
COPY --from=composer /app/vendor ./vendor

# Copy application code (add public/build generated by local npm run build command)
COPY . .

# Clear cached files from COPY
RUN rm -rf bootstrap/cache/*.php \
    && rm -rf storage/framework/cache/data/* \
    && rm -rf storage/framework/views/*.php

# Set permissions
RUN chown -R www-data:www-data /app /tmp/opcache \
    && chmod -R 755 /app/storage \
    && chmod -R 755 /app/bootstrap/cache

# Cache Laravel configurations (without config:cache to use env.yaml info)
RUN php artisan package:discover --ansi \
    && php artisan route:cache \
    && php artisan view:cache \
    && php artisan event:cache

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8080/health || exit 1

CMD ["php", "artisan", "octane:frankenphp", "--host=0.0.0.0", "--port=8080", "--admin-port=2019", "--workers=2", "--max-requests=500"]